### PR TITLE
Feature/user registration steps

### PR DESCRIPTION
**Pull request by qvalentin**
* serialize User to JSON: you maybe want to move this method
* userWithIdIsInGroupWithId: userEntity.setGroupIds(groudIds); was not working idk why?

### CODE REVIEW

**Comment by open-schnick** [comment]
> * serialize User to JSON: you maybe want to move this method
> * userWithIdIsInGroupWithId: userEntity.setGroupIds(groudIds); was not working idk why?

create me a bug task, then i will look into it.

**Comment by open-schnick** [comment]
gonna take a look at this tomorrow.

**Comment by qvalentin** [comment]
@open-schnick then we merge this?

**Review by open-schnick — COMMENTED** [review]
> @open-schnick then we merge this?

sadly not.

**Review by open-schnick — APPROVED** [review]

**Pull request merged**
