### PR TITLE
use plugin to generate swagger.json file 

### PR DESCRIPTION
**Pull request by qvalentin**
https://github.com/springdoc/springdoc-openapi-maven-plugin

### CODE REVIEW

**Review by open-schnick — CHANGES_REQUESTED** [review]
can we not commit the json file itself pls?
Also can you state what command to run and maybe build a workflow to run it. Maybe push the new json file to a different repo with pages

**Comment by qvalentin** [comment]
> can we not commit the json file itself pls?
> Also can you state what command to run and maybe build a workflow to run it. Maybe push the new json file to a different repo with pages

mvn verify

Yes, im still unsure about how we can display it now. I think gitlab can render swagger files, but it seems like github doesn't do this.

**Comment by open-schnick** [comment]
Isnt this mr redundant when using stage profile?

**Comment by qvalentin** [comment]
> Isnt this mr redundant when using stage profile?

yes, we don't need it, but it could still be usefull for converting swagger to postman, maybe?

**Comment by open-schnick** [comment]
ok @qvalentin i am gonna create a workflow and then merge it. Give me time tho

**Comment by qvalentin** [comment]
Ok, but only if it is worth the effort.

**Pull request closed without merging**
