### PR TITLE
FF-245 Implement getFileSystemItemInfo

### PR DESCRIPTION
**Pull request by open-schnick**

### CODE REVIEW

**Review by qvalentin — APPROVED** [review]
why does it not contain the permissions?

**Comment by open-schnick** [comment]
Same reason. If you want it you can ask the permission endpoint. The endpoint returns 400 if you are not in allowed to see it

**Comment by qvalentin** [comment]
> Same reason. If you want it you can ask the permission endpoint. The endpoint returns 400 if you are not in allowed to see it

kk

but then I don't really know what this endpoint will be used for

**Comment by open-schnick** [comment]
DataHandler checks if the file with the id exists and if the user is allowed to download it

**Comment by qvalentin** [comment]
> DataHandler checks if the file with the id exists and if the user is allowed to download it

makes sense

**Pull request merged**
